### ISSUE TITLE
Issues with quarkus-openapi-generator and existing rest-client

### ISSUE THREAD

**Issue by einarjohnson** [quarkiverse/quarkus-openapi-generator#157]
Hello,
When I add the
```  
<dependency>
      <groupId>io.quarkiverse.openapi.generator</groupId>
      <artifactId>quarkus-openapi-generator</artifactId>
      <version>0.11.0</version>
    </dependency>
```
dependency into my POM file for a Quarkus Lambda handler that uses the `quarkus-rest-client-reactive`  extension I start getting weird errors when my rest client implementation tries to contact a GET endpoint. Is the `quarkus-openapi-generator` compatible with the `quarkus-rest-client-reactive` extension? I am using the latest version of Quarkus, **2.13.2.Final**.

The error is:
Caused by: java.lang.IllegalStateException: Expected RestClientBuilder to be an instance of ```
io.quarkus.rest.client.reactive.runtime.RestClientBuilderImpl, got io.quarkus.restclient.runtime.QuarkusRestClientBuilder
        at io.quarkus.rest.client.reactive.runtime.RestClientCDIDelegateBuilder.build(RestClientCDIDelegateBuilder.java:61)
        at io.quarkus.rest.client.reactive.runtime.RestClientCDIDelegateBuilder.createDelegate(RestClientCDIDelegateBuilder.java:42)
        at io.quarkus.rest.client.reactive.runtime.RestClientReactiveCDIWrapperBase.<init>(RestClientReactiveCDIWrapperBase.java:20)
```

**Comment by ricardozanini** [comment]
Hi @einarjohnson! We are still migrating to the new `quarkus-rest-client-reactive`. See #150. Until then, I believe this extension can't be used with reactive clients. 😞

**Comment by einarjohnson** [comment]
Thank you @ricardozanini for the quick response!

**Comment by ricardozanini** [comment]
Closing this one since we already have #150
