### ISSUE TITLE
Regression from 2.2.2 to 2.2.4 (?) OpenApiGeneratorException Invalid path on quarkus.openapi-generator.codegen.input-base-dir

### ISSUE THREAD

**Issue by laurentperez** [quarkiverse/quarkus-openapi-generator#343]
Hi

Updating from 2.2.2 to 2.2.4 build now throws at compile time

```
Caused by: io.quarkiverse.openapi.generator.OpenApiGeneratorException: Invalid path on quarkus.openapi-generator.codegen.input-base-dir: /home/lperez/Bureau/work/xxxxxxx/server/build/classes/java/quarkus-generated-sources/openapi
        at io.quarkiverse.openapi.generator.deployment.codegen.OpenApiGeneratorCodeGenBase.lambda$shouldRun$1(OpenApiGeneratorCodeGenBase.java:79)
        at io.quarkiverse.openapi.generator.deployment.codegen.OpenApiGeneratorCodeGenBase.shouldRun(OpenApiGeneratorCodeGenBase.java:72)
        at io.quarkus.deployment.CodeGenerator.lambda$trigger$3(CodeGenerator.java:175)
```

I had not defined `quarkus.openapi-generator.codegen.input-base-dir`.

However, defining it to `quarkus.openapi-generator.codegen.input-base-dir=openapi` or src/main/openapi has no effect. It seems the deployment phase assumes `build/classes/java/quarkus-generated-sources/openapi` is the input base.

Can anyone confirm ? May be related to #192 #314 and https://github.com/quarkiverse/quarkus-openapi-generator/issues/192#issuecomment-1522210657

**Comment by laurentperez** [comment]
Problem/regression is caused by usage of `sourcesSets` as below in a gradle build. Definition below was working under 2.2.2. Since 2.2.4, it throws setting "openapi" as a replacement string to the trailing end of a sourceSet.

Note : my codebase is Kotlin. I'm using java sourceSets to mark them as source code for IDE and compilation.

```
sourceSets {
    main {
        java {
            setSrcDirs(setOf(
                "src/main/kotlin",
                "build/classes/java/quarkus-generated-sources/open-api-json"))
        }
    }
}
```

**Comment by hbelmiro** [comment]
Hi @laurentperez. Thanks for reporting.
Would you mind sharing a reproducer? I just tested it (with Maven) and it works.

**Comment by laurentperez** [comment]
@hbelmiro this is https://github.com/quarkiverse/quarkus-openapi-generator/pull/345

- steps : I created a minimal project using bootstrap from https://code.quarkus.io/
- added `implementation("io.quarkiverse.openapi.generator:quarkus-openapi-generator:2.2.4")`
- created src/main/openapi (but this was not needed. bug happens without requiring a folder)

`./gradlew clean assemble --stacktrace`

```
Caused by: io.quarkiverse.openapi.generator.OpenApiGeneratorException: Invalid path on quarkus.openapi-generator.codegen.input-base-dir: /home/lperez/Bureau/work/quarkus-openapi-generator/repro/build/classes/java/openapi
        at io.quarkiverse.openapi.generator.deployment.codegen.OpenApiGeneratorCodeGenBase.lambda$shouldRun$1(OpenApiGeneratorCodeGenBase.java:79)
        at io.quarkiverse.openapi.generator.deployment.codegen.OpenApiGeneratorCodeGenBase.shouldRun(OpenApiGeneratorCodeGenBase.java:72)
        at io.quarkus.deployment.CodeGenerator.lambda$trigger$3(CodeGenerator.java:175)

```
